apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  port:
    targetPort: 8080-tcp
  host: spring-petclinic-zbtest-spring-petclinic.apps.microshift02.ocp.mindray.com
  to:
    kind: Service
    name: spring-petclinic
    weight: 100
