apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: spring-petclinic
  namespace: zbtest-spring-petclinic
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - spring-petclinic