apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: parksmap
  name: parksmap-placement-hub
  namespace: parksmap
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster
status:
  decisions:
    - clusterName: local-cluster
      clusterNamespace: local-cluster
