apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-path: apps/spring-petclinic/overlays/hub
    apps.open-cluster-management.io/reconcile-option: merge
  generation: 1
  labels:
    app: spring-petclinic
    app.kubernetes.io/part-of: spring-petclinic
    apps.open-cluster-management.io/reconcile-rate: medium
  name: spring-petclinic-subscription-hub
  namespace: spring-petclinic
spec:
  channel: >-
    ggithubcom-xdevops-caj-lab-gitops-acm-repo-example-ns/ggithubcom-xdevops-caj-lab-gitops-acm-repo-example
  placement:
    placementRef:
      kind: PlacementRule
      name: spring-petclinic-placement-hub

