apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: parksmap
  name: parksmap-placement-ocp1
  namespace: parksmap
spec:
  clusterSelector:
    matchLabels:
      name: ocp1
status:
  decisions:
    - clusterName: ocp1
      clusterNamespace: ocp1
