apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: apps/parksmap/overlays/uat
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: parksmap
    app.kubernetes.io/part-of: parksmap
    apps.open-cluster-management.io/reconcile-rate: medium
  name: parksmap-subscription-uat
  namespace: zbtest-parksmap
spec:
  channel: >-
    zbtest-acm-repo-example/acm-repo-example
  placement:
    placementRef:
      kind: PlacementRule
      name: parksmap-placement-uat

