apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-path: apps/parksmap/overlays/hub
    apps.open-cluster-management.io/reconcile-option: merge
  generation: 1
  labels:
    app: parksmap
    app.kubernetes.io/part-of: parksmap
    apps.open-cluster-management.io/reconcile-rate: medium
  name: parksmap-subscription-hub
  namespace: parksmap
spec:
  channel: >-
    ggithubcom-xdevops-caj-lab-gitops-acm-repo-example-ns/ggithubcom-xdevops-caj-lab-gitops-acm-repo-example
  placement:
    placementRef:
      kind: PlacementRule
      name: parksmap-placement-hub

